Resources:
  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties: 
      DBSecurityGroupIngress: 
        -  CIDRIP: '0.0.0.0/0'
      GroupDescription: 'Group for Lambda Access'
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      Engine: postgres
      EngineVersion: '11.5'
      AllocatedStorage: '20'
      DBInstanceIdentifier: '${self:service}-${self:provider.stage}-instance'
      DBName: '${self:service}_${self:provider.stage}_db'
      MasterUsername: '${self:provider.environment.DB_USERNAME}'
      MasterUserPassword: '${self:provider.environment.DB_PASSWORD}'
      DBSecurityGroups: 
        - Ref: DBSecurityGroup
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ''
